import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { gql } from '@apollo/client';
import styles from '../styles/Home.module.css';
import useTranslation from 'next-translate/useTranslation';
// import withTranslation from 'next-translate/withTranslation';
// import withTranslation from 'next-translate/withTranslation';
import { initializeApollo } from '../lib/apollo';
// import { t } from 'i18next';
const LIST_CATEGORIES = gql`
  query ListCategories {
    listCategories {
      _id
      name
    }
  }
`;

// import React from 'react';
// import HomeSlider from '../components/HomeSlider/HomeSlider.container';
// import ProductOverviewContainer from '../components/ProductOverview/ProductOverview.container.js';
// import Elementor from '../components/Elementor/Elementor.component.jsx';
// import Widget from '../components/Widget/Widget.component.jsx';
// import { withTranslation } from 'react-i18next';
// import { mapCategory } from '../util/helper';
// import BannerContainer from '../components/Banner';

// const LIST_CATEGORIES = gql`
//   query ListCategories {
//     listCategories {
//       _id
//       name
//     }
//   }
// `;
// class Home extends React.Component {
//   constructor(props) {
//     super(props);
//     this.state = {
//       category: null,
//     };
//   }

//   componentDidMount() {
//     const { categories } = this.props;
//     console.log('im categories');
//     console.log(categories);
//     // //console.log('on did mount')
//     // //console.log(categories)
//     this.setState(() => {
//       return {
//         category: categories[0],
//       };
//     });
//   }

//   renderSections = (category) => {
//     const { region } = this.props;
//     // //console.log(category)
//     if (category && region) {
//       return (
//         <ProductOverviewContainer
//           region={region}
//           key={category._id}
//           category={category}
//         />
//       );
//     }
//   };

//   renderCategory = () => {
//     const { category } = this.state;
//     if (category) {
//       if (this.props.categories.length > 4) {
//         const subCategory = this.props.categories.slice(0, 4);
//         ////console.log(this.state.category)
//         return subCategory.map((item, idx) => {
//           ////console.log(this.state.item._id)
//           return (
//             <p
//               className={category._id === item._id ? 'active' : ''}
//               onClick={() => {
//                 this.setState(() => ({ category: item }));
//               }}
//               key={idx}
//             >
//               {/* {item.name} */}
//               {this.props.t(mapCategory(item.name))}
//             </p>
//           );
//         });
//       } else {
//       }
//     }
//   };
//   render() {
//     return (
//       <section className="container">
//         <Head>
//           <title>Au Lac Shop</title>
//           <meta
//             name="description"
//             content="This is a Website of Au Lac Company"
//           />
//         </Head>
//         <p>Testing</p>
//         <HomeSlider categories={this.props.categories} />
//         <Widget categories={this.props.categories} />
//         <BannerContainer isCenter={true} />
//         <ProductOverviewContainer region={this.props.region} />
//         <div style={{ paddingBottom: '40px' }}>
//           <BannerContainer isCenter={true} />
//         </div>
//         <Elementor />
//       </section>
//     );
//   }
// }
// export default Home;

// export default withTranslation('common')(Home);

// export default function Home() {
//   const { data, loading, error } = useQuery(LIST_CATEGORIES);
//   if (loading) {
//     return <h1>Loading...</h1>;
//   }
//   if (error) {
//     return <h1>We have an Error here...</h1>;
//   }
//   const { t, lang } = useTranslation('common');
//   // const { t } = useTranslation('common')
//   console.log('This is the fucking translate');
//   console.log(t('couponStartAtPrice'));
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// }

const Wrapper = (Component) => (props) => {
  const { t, lang } = useTranslation('common');
  return <Component {...props} t={t} language={lang} />;
};
class Home extends React.Component {
  render() {
    const { t, language } = this.props;
    console.log(this.props.categories, t, language);
    return <h1>This use for testing: {t('couponStartAtPrice')} </h1>;
  }
}

export default Wrapper(Home);

export const getStaticProps = async () => {
  const apolloClient = initializeApollo();
  let listCategories = [];
  try {
    await apolloClient.query({
      query: LIST_CATEGORIES,
      // variables: { code: VARIABLE },
    });
    console.log('get data successfully');
    // console.log(apolloClient.cache.extract().listCategories);
    const { listCategories: data } = apolloClient.cache.readQuery({
      query: LIST_CATEGORIES,
    });
    console.log(data);
    listCategories = data;
  } catch (e) {
    console.log(e);
  }
  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
      categories: listCategories,
    },
  };
};
